name: dockerhub Publish CI

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: dockerhub login
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: bash build.sh
      - name: Tag the Docker image
        run: docker tag michaelvaldron/hugo docker.io/michaelvaldron/hugo:latest
      - name: Publish the Docker image to dockerhub
        run: docker push docker.io/michaelvaldron/hugo:latest
