name: dockerhub Publish CI

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: dockerhub login
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: bash build.sh
      - name: Tag the Docker image
        run: docker tag michaelvaldron/hugo docker.io/michaelvaldron/hugo:latest
      - name: Publish the Docker image to dockerhub
        run: docker push docker.io/michaelvaldron/hugo:latest
