name: dockerhub Publish CI

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: dockerhub login
        uses: docker/login-action@eb1ca82ebd6f2efb2935cf54c961d6682e188ce2 # v3.0.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag michaelvaldron/hugo
      - name: Tag the Docker image
        run: docker tag michaelvaldron/hugo docker.io/michaelvaldron/hugo:latest
      - name: Publish the Docker image to dockerhub
        run: docker push docker.io/michaelvaldron/hugo:latest
