name: dockerhub Publish CI

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
          - latest
          - go1.23
          - go1.24
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: dockerhub login
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: bash build.sh "${{ matrix.tag }}"
      - name: Publish the Docker image to dockerhub
        run: docker push docker.io/michaelvaldron/hugo:${{ matrix.tag }}
