name: Docker Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Build the Docker images
        run: |
          TAGS="$(ls build)"
          for tag in $TAGS; do 
            echo -n "Building '${tag}'... "
            bash build.sh "${tag}"
            echo "Done!"
          done
